Models/ErrorViewModel.cs
namespace VeiculosMVC.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/SolicitacaoModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace VeiculosMVC.Models
{
    public class SolicitacaoModel
    {
    public int Id { get; set; }
    public int UsuarioId { get; set; }
    public int VeiculoId { get; set; }
    public string Nome { get; set; }
    public string Email { get; set; }
    public string Telefone { get; set; }
    public DateTime DataInicio { get; set; }
    public DateTime DataFim { get; set; }
    public string Status { get; set; } // "Pendente", "Aprovada", "Rejeitada"
    [ForeignKey("UsarioId")]
    public UsuarioModel Usuario { get; set; }

    [ForeignKey("VeiculoId")]
    public VeiculoModel Veiculo { get; set; }
    }
}

Models/SolicitacaoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using VeiculosMVC.Models;

namespace locadoraMVCSenai.Models
{
    public class SolicitacaoViewModel
    {
        public VeiculoModel Veiculo { get; set; }
        public SolicitacaoModel Solicitacao { get; set; }
        public decimal TotalDias { get; set; }
        public decimal ValorTotal { get; set; }
    }
}

Models/UsuarioModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace VeiculosMVC.Models
{
    public class UsuarioModel
    {
    public int Id { get; set; }
    public string Nome { get; set; }
    public string Email { get; set; }
    public string Senha { get; set; }
    public bool IsAdmin { get; set; }
    }
}

Models/VeiculoModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace VeiculosMVC.Models
{
    public class VeiculoModel
{    
    public int Id { get; set; }
    public string Modelo { get; set; }
    public string Marca { get; set; }
    public decimal PrecoPorDia { get; set; }
    public string FotoUrl { get; set; }
    public bool Disponivel { get; set; } = true;
}
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using VeiculosMVC.Models;

namespace VeiculosMVC.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/SolicitacoesController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using locadoraMVCSenai.Models;
using locadoraMVCSenai.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using VeiculosMVC.Data;
using VeiculosMVC.Models;
using VeiculosMVC.Repository;

namespace VeiculosMVC.Controllers
{
    public class SolicitacoesController : Controller
    {
        private readonly IVeiculosRepository _veiculosRepository;

        private readonly LocadoraContext _locadoraContext;

        private readonly ISolicitacoesRepository _solicitacoesRepository;

        public SolicitacoesController(IVeiculosRepository veiculosRepository, ISolicitacoesRepository solicitacaoRepository)
        {
            _solicitacoesRepository = solicitacaoRepository;
            _veiculosRepository = veiculosRepository;
        }

        public IActionResult Index(){
            return View();
        }

        public IActionResult Criar(int id)
        {
            var veiculos = _veiculosRepository.ListarId(id);
            var solicitacao = new SolicitacaoModel();
            
            var ViewModel = new SolicitacaoViewModel{
                Veiculo = veiculos,
                Solicitacao = solicitacao
            };

            return View(ViewModel);
        }

        [HttpPost]
        public IActionResult Criar(SolicitacaoModel solicitacao)
        {
            if(ModelState.IsValid){
                _solicitacoesRepository.Adicionar(solicitacao);
                return RedirectToAction("Index");
            }
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Controllers/VeiculosController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using VeiculosMVC.Models;
using VeiculosMVC.Repository;

namespace VeiculosMVC.Controllers
{
    public class VeiculosController : Controller
    {
        private readonly IVeiculosRepository _veiculosRepository;

        public VeiculosController(IVeiculosRepository veiculosRepository)
        {
            _veiculosRepository = veiculosRepository;
        }

        public IActionResult Index()
        {
            var veiculos = _veiculosRepository.ListarVeiculos();
            return View(veiculos);
        }

        public IActionResult Criar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Criar(VeiculoModel veiculo)
        {
            if (ModelState.IsValid)
            {
                _veiculosRepository.Adicionar(veiculo);
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Editar(int id)
        {
            VeiculoModel veiculo = _veiculosRepository.ListarId(id);
            return View(veiculo);
        }
        [HttpPost]
        public IActionResult Editar(VeiculoModel veiculo)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _veiculosRepository.Editar(veiculo);
                    TempData["MensagemSucesso"] = "Veiculo alterado com sucesso!";
                    return RedirectToAction("Index");
                }
                return View("Editar", veiculo);
            }
            catch (Exception error)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos atualizar seu veiculo, tente novamente!, detalhe do erro:{error.Message}";
                return RedirectToAction("Index");
            }

        }

        public IActionResult VerificarDeletar(int id)
        {
            VeiculoModel veiculo = _veiculosRepository.ListarId(id);
            return View(veiculo);
        }

        public IActionResult Apagar(int id)
        {
            try
            {
               bool apagar = _veiculosRepository.Deletar(id);
                if (apagar)
                {
                    TempData["MensagemSucesso"] = "Contato apagado com sucesso!";
                }
                else
                {
                    TempData["MensagemErro"] = $"Ops, não conseguimos apagar seu contato!";
                }
                return RedirectToAction("Index");
            }
            catch(Exception error)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos apagar seu contato, tente novamente!, detalhe do erro:{error.Message}";
                return RedirectToAction("Index");
            }
        }

            [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
            public IActionResult Error()
            {
             return View("Error!");
            }
    }
 }

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Início";
}

<div class="hero">
    <h1 class="display-3 text-center text-success">Bem-vindo à Locadora de Veículos</h1>
    <p class="lead text-center">A melhor opção para alugar carros e motos de qualidade.</p>
    
    <div id="carouselExampleAutoplaying" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhTyhRuNDG4N8dtsfb08q4r1c3Lk-LMeBpwmslkPk-GDodNU5YsP-7C4jRrPPBVlNhxzpQe3MoM0Jo8ba29PKE_K4DwDDLci-AsHL25JAKg891nVv-DdHsYmbADIsHpnFtMftVv0SA-iqWJ/s1600/real-strong-car-1920x1200.jpg" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="https://painel.automotivebusiness.com.br/wp-content/uploads/2024/10/dodge-charger-04.jpg__1600.0x900.0_q85_subsampling-2.jpg" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="https://wallpaperaccess.com/full/4665561.jpg" class="d-block w-100" alt="...">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
<a href="/Veiculos" class="btn btn-success btn-lg">Veja nossos veículos</a>
</div>

<div class="container my-4">
    <h2 class="text-center mb-4 text-success">Nossos Serviços</h2>
    <div class="row">
        <div class="col-md-4">
            <div class="card service-card">
                <div class="card-body text-center">
                    <h5 class="card-title">Aluguel de Carros</h5>
                    <p class="card-text">Uma ampla variedade de carros para atender às suas necessidades.</p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card service-card">
                <div class="card-body text-center">
                    <h5 class="card-title">Adicionais</h5>
                    <p class="card-text">Motos econômicas e práticas para o seu dia a dia.</p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card service-card">
                <div class="card-body text-center">
                    <h5 class="card-title">Portal do Cliente</h5>
                    <p class="card-text">Tudo que você precisa, em um só lugar.</p>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container my-5">
    <h2 class="text-center text-success">Conheça a nossa Frota</h2>
    <p class="text-center">As melhores condições para você reservar e aproveitar.</p>
    
    <div id="frotaCarousel" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <div class="d-flex justify-content-center">
                    <div class="card mx-2" style="width: 18rem;">
                        <img src="https://diariodopara.com.br/wp-content/uploads/2023/04/fffb2e94-be3d-4b05-b3cd-659bf3f728fb_1365x1024-1024x575.jpg" class="card-img-top" alt="Executivo Elétrico">
                        <div class="card-body text-center">
                            <h5 class="card-title">Grupo FE - Executivo Elétrico</h5>
                            <p class="card-text">Veículo similar a: GM Bolt Premier Elétrico, dentre outros.</p>
                        </div>
                    </div>
                    <div class="card mx-2" style="width: 18rem;">
                        <img src="https://seminovos.unidas.com.br/blog/content/uploads/2023/07/6-opcoes-de-carros-populares-1024x575.png" class="card-img-top" alt="Localiza Prime">
                        <div class="card-body text-center">
                            <h5 class="card-title">Grupo LP - Localiza Prime</h5>
                            <p class="card-text">Veículo similar a: Audi A3 Sedan S Line AT Hybrid, dentre outros.</p>
                        </div>
                    </div>
                    <div class="card mx-2" style="width: 18rem;">
                        <img src="https://monitormercantil.com.br/wp-content/uploads/2023/06/Polo-foto-Volkswagen-1-1024x575.png.webp" class="card-img-top" alt="Localiza Prime">
                        <div class="card-body text-center">
                            <h5 class="card-title">Grupo LP - Localiza Prime</h5>
                            <p class="card-text">Veículo similar a: Audi A3 Sedan S Line AT Hybrid, dentre outros.</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <div class="d-flex justify-content-center">
                    <div class="card mx-2" style="width: 18rem;">
                        <img src="https://cdn.oantagonista.com/uploads/2024/07/1_azure_panda_emall66179aa5e4b00ac67f7dbf19-38778545-1024x575.png" class="card-img-top" alt="Executivo Blindado">
                        <div class="card-body text-center">
                            <h5 class="card-title">Grupo T - Executivo Blindado</h5>
                            <p class="card-text">Veículo similar a: Toyota Corolla 2.0, dentre outros.</p>
                        </div>
                    </div>
                    <div class="card mx-2" style="width: 18rem;">
                        <img src="https://99app.com/wp-content/uploads/2023/05/Fiat_Argo_Drive_CVT-1024x575.jpg" class="card-img-top" alt="Executivo Blindado">
                        <div class="card-body text-center">
                            <h5 class="card-title">Grupo T - Executivo Blindado</h5>
                            <p class="card-text">Veículo similar a: Toyota Corolla 2.0, dentre outros.</p>
                        </div>
                    </div>
                    <div class="card mx-2" style="width: 18rem;">
                        <img src="https://blog.multiplaprotecao.com/wp-content/uploads/2024/01/Onix-1024x575.png" class="card-img-top" alt="Executivo Blindado">
                        <div class="card-body text-center">
                            <h5 class="card-title">Grupo T - Executivo Blindado</h5>
                            <p class="card-text">Veículo similar a: Toyota Corolla 2.0, dentre outros.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#frotaCarousel" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#frotaCarousel" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
        </button>
    </div>

    <div class="text-center mt-3">
        <a href="/Frota" class="btn btn-outline-success">Conferir todos os grupos</a>
    </div>
</div>


<div class="container my-5">
    <h2 class="text-center text-success">Destinos para descobrir e se inspirar</h2>
    <p class="text-center">Mais do que alugar carros, nós cuidamos do seu caminho. Confira as nossas dicas de viagem para inspirar sua próxima experiência.</p>
    
    <div id="destinosCarousel" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <div class="d-flex justify-content-center">
                    <div class="card mx-2" style="width: 18rem;">
                        <img src="https://cdn.blablacar.com/wp-content/uploads/br/2023/12/05102931/icarai-niteroi-rj.webp" class="card-img-top" alt="Niterói">
                        <div class="card-body text-center">
                            <h5 class="card-title">O que fazer em Niterói, RJ?</h5>
                            <p class="card-text text-muted">RIO DE JANEIRO</p>
                        </div>
                    </div>
                    <div class="card mx-2" style="width: 18rem;">
                        <img src="https://jpimg.com.br/uploads/2024/07/veja-como-aproveitar-as-ferias-em-joao-pessoa.jpg" class="card-img-top" alt="João Pessoa">
                        <div class="card-body text-center">
                            <h5 class="card-title">O que fazer em João Pessoa?</h5>
                            <p class="card-text text-muted">PARAÍBA</p>
                        </div>
                    </div>
                    <div class="card mx-2" style="width: 18rem;">
                        <img src="https://www.direcional.com.br/wp-content/uploads/2021/08/bahia-2-3.jpg" class="card-img-top" alt="João Pessoa">
                        <div class="card-body text-center">
                            <h5 class="card-title">O que fazer em Salvador, BA?</h5>
                            <p class="card-text text-muted">BAHIA</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <div class="d-flex justify-content-center">
                    <div class="card mx-2" style="width: 18rem;">
                        <img src="https://www.remessaonline.com.br/blog/wp-content/uploads/2024/10/brasilia.jpg.optimal.jpg" class="card-img-top" alt="Brasília">
                        <div class="card-body text-center">
                            <h5 class="card-title">O que fazer em Brasília, DF?</h5>
                            <p class="card-text text-muted">DISTRITO FEDERAL</p>
                        </div>
                    </div>
                    <div class="card mx-2" style="width: 18rem;">
                        <img src="https://www.remessaonline.com.br/blog/wp-content/uploads/2024/10/ouro-preto.jpg.optimal.jpg" class="card-img-top" alt="Ouro Preto">
                        <div class="card-body text-center">
                            <h5 class="card-title">O que fazer em Ouro Preto, MG?</h5>
                            <p class="card-text text-muted">MINAS GERAIS</p>
                        </div>
                    </div>
                    <div class="card mx-2" style="width: 18rem;">
                        <img src="https://media.staticontent.com/media/pictures/04641818-297a-4f28-b635-b15e2fb31087" class="card-img-top" alt="Ouro Preto">
                        <div class="card-body text-center">
                            <h5 class="card-title">O que fazer em Curitiba, PA?</h5>
                            <p class="card-text text-muted">PARANÁ</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#destinosCarousel" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#destinosCarousel" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
        </button>
    </div>

    <div class="text-center mt-3">
        <a href="/Destinos" class="btn btn-outline-success">Conferir todos os destinos</a>
    </div>
</div>

Views/Solicitacoes/Criar.cshtml
@using locadoraMVCSenai.Models
@model SolicitacaoViewModel

@{
    ViewData["Title"] = "Solicitar Veículo";
    
    DateTime dataInicio = Model.Solicitacao.DataInicio;
    DateTime dataFim = Model.Solicitacao.DataFim;
    decimal totalDias = 0;
    decimal valorTotal = 0;
    
        totalDias = (decimal)(dataFim - dataInicio).TotalDays;
}

<div class="container my-5">
    <p>@totalDias;</p>
    <form asp-controller="Solicitacoes" asp-action="Criar" method="post">
        <input type="hidden" name="VeiculoId" value="@Model.Veiculo.Id" />
        <h2 class="text-center">Solicitar Veículo</h2>
        <p><strong>Veículo:</strong> @Model.Veiculo.Modelo</p>
        <p><strong>Preço por Dia:</strong> R$@Model.Veiculo.PrecoPorDia.ToString("F2")</p>
        <div class="text-center">
            <img src="@Model.Veiculo.FotoUrl" alt="" class="w-50 rounded">
        </div>
        <div class="mb-3">
            <label for="DataInicio" class="form-label">Data de Início</label>
            <input type="date" class="form-control" asp-for="Solicitacao.DataInicio" id="DataInicio" required />
            <label for="DataTermino" class="form-label">Data de Término</label>
            <input type="date" class="form-control" asp-for="Solicitacao.DataFim" id="DataTermino" required />
        </div>

        <div class="mb-3">
            <label for="NomeUsuario" class="form-label">Nome</label>
            <input type="text" asp-for="Solicitacao.Nome" class="form-control" id="NomeUsuario" required />
        </div>

        <div class="mb-3">
            <label for="EmailUsuario" class="form-label">E-mail</label>
            <input type="email" asp-for="Solicitacao.Email" class="form-control" id="EmailUsuario" required />
        </div>

        <div class="mb-3">
            <label for="TelefoneUsuario" class="form-label">Telefone</label>
            <input type="tel" asp-for="Solicitacao.Telefone" class="form-control" id="TelefoneUsuario" required />
        </div>

        <!-- Exibir a diferença de dias calculada -->
        <div class="mb-3">
            <label for="TotalDias" class="form-label">Total de Dias</label>
            <input type="text" class="form-control" id="TotalDias"  readonly />
        </div>

        <div class="mb-3">
            <label for="ValorTotal" class="form-label">Valor Total</label>
            <input type="text" class="form-control" id="ValorTotal" readonly />
        </div>

        <button type="submit" class="btn btn-primary">Enviar Solicitação</button>
        <a type="button" class="btn btn-secondary" asp-controller="Veiculos" asp-action="Index">Voltar</a>
    </form>
</div>

Views/Solicitacoes/Index.cshtml
@{
    ViewData["Title"] = "Solicitação de Veículo";
}

<h1>@ViewData["Title"]</h1>

<div class="container my-5">
    <table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">First</th>
      <th scope="col">Last</th>
      <th scope="col">Handle</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>Mark</td>
      <td>Otto</td>
      <td>do</td>
    </tr>
    <tr>
      <th scope="row">2</th>
      <td>Jacob</td>
      <td>Thornton</td>
      <td>fat</td>
    </tr>
    <tr>
      <th scope="row">3</th>
      <td colspan="2">Larry the Bird</td>
      <td>twitter</td>
    </tr>
  </tbody>
</table>
</div>

Views/Veiculos/Criar.cshtml
@model VeiculoModel

@{
    ViewData["Title"] = "Lista de Veículos";
}

<form asp-controller="Veiculos" asp-action="Criar" method="post">
<div class="container my-5">
    <h2 class="text-center">Cadastrar Veiculo</h2>

    <div class="mb-3">
    <label for="Modelo" class="form-label">Modelo</label>
    <input type="text" asp-for="Modelo" class="form-control" id="Modelo" placeholder="Digite o Modelo do carro">
    </div>

    <div class="mb-3">
    <label for="Marca" class="form-label">Marca</label>
    <input type="text" asp-for="Marca" class="form-control" id="Marca" placeholder="Digite a Marca do carro">
    </div>

    <div class="mb-3">
    <label for="Preco" class="form-label">Preço por dia</label>
    <input type="number" asp-for=PrecoPorDia class="form-control" id="Preco" placeholder="Digite o Preço do carro">
    </div>

    <div class="mb-3">
    <label for="url" class="form-label">URL Foto</label>
    <input type="url" asp-for=FotoUrl class="form-control" id="url" placeholder="Digite a url da Foto do carro">
    </div>
    
    <button type="submit" class="btn btn-success">Confirmar</button>
    <a type="button" class="btn btn-secondary" asp-controller="Veiculos" asp-action="Index">Voltar</a>
</div>
</form>

Views/Veiculos/Editar.cshtml
@model VeiculoModel

@{
    ViewData["Title"] = "Editar Veículo";
}

<form asp-controller="Veiculos" asp-action="Editar" method="post">
    <input type="hidden" asp-for="Id">
<div class="container my-5">
    <h2 class="text-center">Editar Veiculo</h2>

    <div class="mb-3">
    <label for="Modelo" class="form-label">Modelo</label>
    <input type="text" asp-for="Modelo" class="form-control" id="Modelo" placeholder="Digite o Modelo do carro">
    @Html.ValidationMessageFor(x => x.Modelo)
    </div>

    <div class="mb-3">
    <label for="Marca" class="form-label">Marca</label>
    <input type="text" asp-for="Marca" class="form-control" id="Marca" placeholder="Digite a Marca do carro">
    @Html.ValidationMessageFor(x => x.Marca)
    </div>

    <div class="mb-3">
    <label for="Preco" class="form-label">Preço por dia</label>
    <input type="number" asp-for=PrecoPorDia class="form-control" id="Preco" placeholder="Digite o Preço do carro">
    @Html.ValidationMessageFor(x => x.PrecoPorDia)
    </div>

    <div class="mb-3">
    <label for="url" class="form-label">URL Foto</label>
    <input type="url" asp-for=FotoUrl class="form-control" id="url" placeholder="Digite a url da Foto do carro">
    @Html.ValidationMessageFor(x => x.FotoUrl)
    </div>
    
    <button type="submit" class="btn btn-success">Confirmar</button>
    <a type="button" class="btn btn-secondary" asp-controller="Veiculos" asp-action="Index">Voltar</a>
    
</div>
</form>

Views/Veiculos/Index.cshtml
@model List<VeiculoModel>
@{
    ViewData["Title"] = "Lista de Veículos";
}

<div class="container my-5">
    <h2 class="text-center">Lista de Veículos Disponíveis</h2>
    <a role="button" class="btn btn-primary" asp-controller="Veiculos" asp-action="Criar">+Adicionar veículo</a>
    <br/>

    @if(TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
            @TempData["MensagemSucesso"]
        </div>
    }
    
    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
            @TempData["MensagemErro"]
        </div>
    }

    <!-- Lista de Veículos -->
    <div class="row">
        @if(Model != null && Model.Any()){
        @foreach(var veiculo in Model)
        {
            <div class="col-md-4 mb-4">
                <div class="card h-100">
                    <img src="@veiculo.FotoUrl" class="card-img-top">
                    <div class="card-body">
                        <h5 class="card-title">@veiculo.Modelo</h5>
                        <p class="card-text"><strong>Marca:</strong> @veiculo.Marca</p>
                        <p class="card-text"><strong>Preço por dia:</strong> R$@veiculo.PrecoPorDia.ToString("F2")</p>
                    </div>
                    <div class="card-footer text-center">
                        <a  class="btn btn-success" asp-route-id="@veiculo.Id" asp-controller="Solicitacoes" asp-action="Criar">Reservar</a>
                        <a role="button" class="btn btn-primary" asp-controller="Veiculos" asp-action="Editar" asp-route-id="@veiculo.Id">Editar</a>
                        <a role="button" class="btn btn-danger" asp-route-id="@veiculo.Id" asp-controller="Veiculos" asp-action="VerificarDeletar">Excluir</a>
                    </div>
                </div>
            </div>
        }
        }
    </div>
</div>

Views/Veiculos/VerificarDeletar.cshtml
@model VeiculoModel

@{
    ViewData["Title"] = "Lista de Veículos";
}

<div class="text-center">
    <h2>Realmente deseja apagar o Veiculo (@Model.Modelo)? </h2>
    <img src="@Model.FotoUrl" alt="">
    <a class="btn btn-primary w-100 mb-1" role="button" asp-controller="Veiculos" asp-action="Index">Cancelar exclusão</a>
<a class="btn btn-danger w-100" role="button" asp-controller="Veiculos" asp-action="Apagar" asp-route-id="@Model.Id">Confirmar exclusão</a>
</div>